### ISSUE TITLE
Something funny going on

### ISSUE THREAD

**Issue by bkj** [kylemcdonald/CloudToGrid#1]
Hey --

It seems like there something funny going on here in the interaction between `hungarian` and `lapjv`.  If you run `lapjv.lapjv(cost)` after running `hungarian.lap(cost)`, then it runs very fast (< 1 second, as reported in your notebook).  However, if you run `lapjv` _without_ first running `hungarian`, it takes _way_ longer (> 20 seconds on my machine).  Looking closer, `hungarian.lap(cost)` actually modifies `cost`, which is unexpected.  Any ideas?

~ Ben

**Comment by kylemcdonald** [comment]
thanks! i suspected something like this was happening but never got too deep into it.

before the core of the JV algorithm kicks in, the cost matrices go through an initial set of "reduction" steps to convert them to a form that is easier to work with. if the hungarian algorithm already did some complex reductions (which i think it did) then the JV algorithm can run faster.

i changed the notebook to use `np.copy` to avoid this mistake.

but if you really want better performance out of the JV algorithm, make sure to cast to integers first and you should get back most of that speed. sorry for misleading!

closed by 8993036fc04176779f3f0d368a6efce7e1b36e5d
